# This is the configuration used to check the rubocop source code.
AllCops:
  Include:
    - "**/Gemfile"
    - "**/Rakefile"
    - "bin/*"
    - "*.gemspec"
    - "lib/**/*.rb"
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 40

Metrics/LineLength:
  Max: 80

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 40

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Next:
  Enabled: false

Documentation:
  Enabled: false
